/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("lld.kotlin-library-conventions")
}


dependencies {
    // third-party
    implementation("org.slf4j:slf4j-api:1.7.25")
}
